#!/bin/bash

[ $# != 1 ] && {
echo "usage: hider [file]"
exit
}

grep "^$(basename ${1})$" "$(dirname ${1})/.hidden" &>/dev/null && {
    sed -i "/^$(basename ${1} | sed -e 's/[]\/$*.^[]/\\&/g')$/d" $(dirname ${1})/.hidden
    echo "This file has been set as visible."
} || {
    echo "$(basename ${1})" >>"$(dirname ${1})/.hidden"
    echo "This file has been set as hidden."
}
